
#define SIGNUP "signup"
#define LOGIN "login"
#define LOGOUT "logout"
#define PASSWORD "password"
#define USERNAME "username"
#define ARG_FOLLOWS "?"
#define GETT "GET"
#define TYPE_POSITION 8
#define SCORE_POS 4
#define SCORE "score"
#define SCORE_KEYWORD 3
#define EMAIL "email"
#define MONEY "money"
#define SUPPLIER_SIGNUP "signup_supplier"
#define NAME "name"
#define ORDERS "orders"
#define INGREDIENT "ingredient"
#define INGREDIENTS "ingredients"
#define OFFERS "offers"
#define COUNT "count"
#define PRICE "price"
#define PACKAGING "packaging"
#define CREDITS "credits"
#define TYPE_KEYWORD 7
#define RATES "rates"
#define RECIPES "recipes"
#define MY_RECIPES "my_recipes"
#define RECIPE_ID_POSITION 4
#define RECIPE_ID_KEYWORD 3
#define SIGNUP_CM_SIZE 9
#define LOGIN_SIZE 6
#define SHELVES "shelves"
#define SHELVES_RECIPES "shelves_recipes"
#define PUT "PUT"
#define USERS "users"
#define RATE_SIZE 7
#define NOT_FOUND "not_found"
#define CHEFS "chefs"
#define DELETE "DELETE"
#define TYPE "type"
#define POSTT "POST"
#define BAD_REQUEST "bad_request"
#define RECIPE_ID "recipe_id"
#define ID "id"
#define EMPTY "Empty"
#define GENERAL_TYPE 0
#define DETAILED_RECIPE_SIZE 5
#define CREATE_SHELF_CM_SIZE 5
#define SPECIFIC_COMMAND 1
#define NODIF "*"
#define CM_ALL_RECIPES_SIZE 2
#define OTHER_ARG_START 2
#define USERNAME_POSITION 4
#define USERNAME_KEYWORD 3
#define PASSWORD_KEYWORD 5
#define PASSWORD_POSITION 6
#define PERMISSION_DENIED "permission_denied"
#define GET_ALL_CHEFS 2
#define GET_ONE_CHEF 5
#define CHEF_USERNAME "chef_username"
#define CHEF "chef"
#define USER "user"
#define RECIPE_CREATION_SIZE 10
#define RECIPIE_DELETION_SIZE 4
#define SHELF "shelves"
#define NAME "name"
#define LIMIT "limit"
#define SHELVES_RECIPES "shelves_recipes"
#define SHELF_ID "shelf_id"
#define MIN_MINUTES "min-minutes"
#define MAX_MINUTES "max-minutes"
#define FILTERS "filters"
#define VEGETARIAN "vegetarian"
#define TAG "tag"
#define TAGS "tags"
#define RECIPE_TITLE "title"
#define MIN_RATING "min_rating"
#define MAX_RATING "max_rating"
#define FILTER_LOCATION 3